main:
  project_name: "nyc_airbnb_public"
  experiment_name: "short_term_rental_pipeline"

wandb:
  project: "nyc_airbnb_public"
  entity: "your_entity_name"
  api_key: "your_wandb_api_key"
  tags: ["mlops", "airbnb", "price_prediction", "public"]

etl:
  sample: "sample.csv"
  min_price: 10
  max_price: 350
  geo_bounds:
    lon_min: -74.25
    lon_max: -73.50
    lat_min: 40.50
    lat_max: 41.20

data_check:
  min_rows: 5
  max_rows: 1000000
  min_price: ${etl.min_price}
  max_price: ${etl.max_price}

modeling:
  test_size: 0.2
  random_seed: 42
  stratify_by: "neighbourhood_group"
  max_tfidf_features: 15
  random_forest:
    n_estimators: 200
    max_depth: null
    max_features: 0.5
    min_samples_split: 2
    min_samples_leaf: 1
